services:
  clasp:
    build:
      dockerfile_inline: |
        FROM node:26.4.0-bookworm-slim
        RUN apt-get update && \
            apt-get install -y curl && \
            npm -v && \
            npm i -g \
              @google/clasp@3.3.0 \
              @types/google-apps-script@^1.0.81 \
              prettier@3.9.1 \
              typescript@5.8.3
        WORKDIR /app
        ENTRYPOINT [ "clasp" ]
    volumes:
      - login:/root
      - $PWD:/app
      - node_modules:/app/node_modules
volumes:
  login:
    driver: local
  node_modules:
    driver: local
