name: Markdownlint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Check Markdown
        run: docker run --rm -v "$PWD:/work" -w /work davidanson/markdownlint-cli2:v0.23.0
